<?php

namespace Database\Seeders;

use App\Models\Equipment;
use App\Models\ReffEquip;
use App\Models\Site;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Ensure Sites exist
        $siteCentral = Site::firstOrCreate(
            ['site_code' => 'SITE-BLI'],
            ['site_name' => 'Site Sangatta / Bengalon Coal Project', 'address' => 'Kalimantan Timur', 'remarks' => 'Active Project']
        );
        $siteWest = Site::firstOrCreate(
            ['site_code' => 'SITE-KUT'],
            ['site_name' => 'Site Kalsel Asam-Asam Project', 'address' => 'Kalimantan Selatan', 'remarks' => 'Active Project']
        );

        $siteId = $siteCentral->id;
        $siteAltId = $siteWest->id;

        // Helper to find ReffEquip by model
        $getReffId = function ($model) {
            return ReffEquip::where('model', 'LIKE', "%{$model}%")->value('id');
        };

        $equipmentList = [
            // ==========================================
            // 1. OHT (Off-Highway Dump Trucks / Haulers)
            // ==========================================
            [
                'unit' => 'OHT-777-01',
                'no' => 101,
                'status' => 'Active',
                'reff_model' => '777F',
                'sn_unit' => 'CAT0777FJDP01234',
                'engine_model' => 'CAT C32 ACERT V12',
                'sn_engine' => 'C32-ENG-99881',
                'eqp_capacity' => '100 Ton / 60.1 m³',
                'no_police' => null,
                'attachment' => 'Dual Slope Heavy Rock Body + Liner Hardox 450',
                'hp_kw' => '1016 HP / 758 kW',
                'year_build' => 2022,
                'date_receive' => '2022-03-15',
                'site_id' => $siteId,
                'remarks' => 'Hauler Utama Pit North East. Kondisi sangat prima.',
            ],
            [
                'unit' => 'OHT-777-02',
                'no' => 102,
                'status' => 'Active',
                'reff_model' => '777F',
                'sn_unit' => 'CAT0777FJDP01235',
                'engine_model' => 'CAT C32 ACERT V12',
                'sn_engine' => 'C32-ENG-99882',
                'eqp_capacity' => '100 Ton / 60.1 m³',
                'no_police' => null,
                'attachment' => 'Dual Slope Heavy Rock Body',
                'hp_kw' => '1016 HP / 758 kW',
                'year_build' => 2022,
                'date_receive' => '2022-03-15',
                'site_id' => $siteId,
                'remarks' => 'Hauler Pit North East.',
            ],
            [
                'unit' => 'OHT-785-01',
                'no' => 103,
                'status' => 'Active',
                'reff_model' => 'HD785-8',
                'sn_unit' => 'KMTHD785800011',
                'engine_model' => 'Komatsu SAA12V140E-3',
                'sn_engine' => 'KMT-12V140-5510',
                'eqp_capacity' => '91 Ton / 60.0 m³',
                'no_police' => null,
                'attachment' => 'Dump Body dengan Exhaust Heating',
                'hp_kw' => '1140 HP / 850 kW',
                'year_build' => 2023,
                'date_receive' => '2023-01-20',
                'site_id' => $siteId,
                'remarks' => 'Hauling batubara jarak jauh.',
            ],
            [
                'unit' => 'OHT-797-01',
                'no' => 104,
                'status' => 'Active',
                'reff_model' => '797F',
                'sn_unit' => 'CAT0797FLA00991',
                'engine_model' => 'CAT C175-20 Quad Turbo V20',
                'sn_engine' => 'C175-20-ENG-001',
                'eqp_capacity' => '400 Ton / 267 m³',
                'no_police' => null,
                'attachment' => 'MSD II Mine Specific Body 400T',
                'hp_kw' => '4000 HP / 2983 kW',
                'year_build' => 2021,
                'date_receive' => '2021-08-10',
                'site_id' => $siteId,
                'remarks' => 'Ultra-Class Haul Truck untuk Big Digger PC8000.',
            ],
            [
                'unit' => 'OHT-930-01',
                'no' => 105,
                'status' => 'Active',
                'reff_model' => '930E-5',
                'sn_unit' => 'KMT930E5000088',
                'engine_model' => 'Komatsu SSDA16V160 AC Electric Drive',
                'sn_engine' => 'KMT-16V160-8812',
                'eqp_capacity' => '320 Ton / 211 m³',
                'no_police' => null,
                'attachment' => 'Electric Drive Dump Body',
                'hp_kw' => '2700 HP / 2014 kW',
                'year_build' => 2022,
                'date_receive' => '2022-06-12',
                'site_id' => $siteId,
                'remarks' => 'Hauler Electric AC Drive.',
            ],
            [
                'unit' => 'ADT-745-01',
                'no' => 106,
                'status' => 'Active',
                'reff_model' => '745C',
                'sn_unit' => 'CAT0745CT500331',
                'engine_model' => 'CAT C18 ACERT',
                'sn_engine' => 'C18-ENG-11223',
                'eqp_capacity' => '45 Ton / 25.0 m³',
                'no_police' => null,
                'attachment' => 'Articulated Body + Tailgate Kit',
                'hp_kw' => '511 HP / 381 kW',
                'year_build' => 2021,
                'date_receive' => '2021-11-05',
                'site_id' => $siteAltId,
                'remarks' => 'Unit Articulated untuk medan berlumpur dan overburden.',
            ],
            [
                'unit' => 'ADT-A60-01',
                'no' => 107,
                'status' => 'Active',
                'reff_model' => 'A60H',
                'sn_unit' => 'VLV0A60HA00412',
                'engine_model' => 'Volvo D16J Turbocharged',
                'sn_engine' => 'VLV-D16J-9011',
                'eqp_capacity' => '60 Ton / 33.6 m³',
                'no_police' => null,
                'attachment' => 'Articulated Heavy Duty Body',
                'hp_kw' => '673 HP / 495 kW',
                'year_build' => 2023,
                'date_receive' => '2023-04-18',
                'site_id' => $siteAltId,
                'remarks' => 'Articulated Hauler 60T.',
            ],

            // ==========================================
            // 2. BIG DIGGERS & EXCAVATORS
            // ==========================================
            [
                'unit' => 'EX-PC8000-01',
                'no' => 201,
                'status' => 'Active',
                'reff_model' => 'PC8000-6',
                'sn_unit' => 'KMT-PC8000-00108',
                'engine_model' => '2x Komatsu SDA16V160 Diesel',
                'sn_engine' => 'ENG-LH-001 / ENG-RH-002',
                'eqp_capacity' => '42.0 m³ Heavy Shovel Bucket',
                'no_police' => null,
                'attachment' => 'Front Shovel Attachment 42 m³',
                'hp_kw' => '4020 HP / 3000 kW (Dual Engine)',
                'year_build' => 2020,
                'date_receive' => '2020-05-10',
                'site_id' => $siteId,
                'remarks' => 'Main Loading Fleet Pit Central. Big Digger 800 Ton.',
            ],
            [
                'unit' => 'EX-EX5500-01',
                'no' => 202,
                'status' => 'Active',
                'reff_model' => 'EX5500-6',
                'sn_unit' => 'HIT-EX5500-60012',
                'engine_model' => '2x Cummins QSK50 Tier 2',
                'sn_engine' => 'CUM-QSK50-LH / CUM-QSK50-RH',
                'eqp_capacity' => '29.0 m³ Backhoe Bucket',
                'no_police' => null,
                'attachment' => 'Backhoe Heavy Rock Bucket 29 m³',
                'hp_kw' => '2800 HP / 2088 kW',
                'year_build' => 2021,
                'date_receive' => '2021-02-14',
                'site_id' => $siteId,
                'remarks' => 'Big Digger Loading Overburden.',
            ],
            [
                'unit' => 'EX-390F-01',
                'no' => 203,
                'status' => 'Active',
                'reff_model' => '390F',
                'sn_unit' => 'CAT0390FLA00412',
                'engine_model' => 'CAT C18 ACERT',
                'sn_engine' => 'C18-390F-8819',
                'eqp_capacity' => '6.0 m³ Heavy Duty Rock Bucket',
                'no_police' => null,
                'attachment' => 'Heavy Duty Reach Boom 10.0m + Stick 4.4m',
                'hp_kw' => '543 HP / 405 kW',
                'year_build' => 2022,
                'date_receive' => '2022-07-01',
                'site_id' => $siteId,
                'remarks' => 'Excavator kelas 90 Ton untuk Coal Loading.',
            ],
            [
                'unit' => 'EX-PC800-01',
                'no' => 204,
                'status' => 'Active',
                'reff_model' => 'PC800SE-8',
                'sn_unit' => 'KMT-PC800-88102',
                'engine_model' => 'Komatsu SAA6D140E-5',
                'sn_engine' => '6D140-PC800-112',
                'eqp_capacity' => '4.5 m³ Severe Duty Bucket',
                'no_police' => null,
                'attachment' => 'Short Boom 7.1m + Stick 2.8m (Super Earth Mover)',
                'hp_kw' => '494 HP / 368 kW',
                'year_build' => 2021,
                'date_receive' => '2021-09-20',
                'site_id' => $siteAltId,
                'remarks' => 'Excavator 80 Ton untuk Quarry & Loading.',
            ],
            [
                'unit' => 'EX-349F-01',
                'no' => 205,
                'status' => 'Active',
                'reff_model' => '349F',
                'sn_unit' => 'CAT0349FLA01928',
                'engine_model' => 'CAT C13 ACERT',
                'sn_engine' => 'C13-349F-9921',
                'eqp_capacity' => '3.2 m³ General Duty Bucket',
                'no_police' => null,
                'attachment' => 'Standard Boom 6.9m + Quick Coupler',
                'hp_kw' => '417 HP / 311 kW',
                'year_build' => 2023,
                'date_receive' => '2023-02-11',
                'site_id' => $siteAltId,
                'remarks' => 'Excavator 50 Ton untuk stripping & drainage.',
            ],
            [
                'unit' => 'EX-PC200-01',
                'no' => 206,
                'status' => 'Active',
                'reff_model' => 'PC200-8',
                'sn_unit' => 'KMT-PC200-800912',
                'engine_model' => 'Komatsu SAA6D107E-1',
                'sn_engine' => '6D107-PC200-551',
                'eqp_capacity' => '1.0 m³ Trenching Bucket',
                'no_police' => null,
                'attachment' => 'Standard Bucket + Hydraulic Breaker Piping',
                'hp_kw' => '148 HP / 110 kW',
                'year_build' => 2020,
                'date_receive' => '2020-08-15',
                'site_id' => $siteId,
                'remarks' => 'Excavator Utility / Workshop & Sump Maintenance.',
            ],

            // ==========================================
            // 3. BULLDOZERS (Track Dozers)
            // ==========================================
            [
                'unit' => 'DZ-D375-01',
                'no' => 301,
                'status' => 'Active',
                'reff_model' => 'D375A-8',
                'sn_unit' => 'KMT-D375A-80021',
                'engine_model' => 'Komatsu SAA6D170E-7',
                'sn_engine' => '6D170-D375-771',
                'eqp_capacity' => '18.5 m³ Semi-U Blade',
                'no_police' => null,
                'attachment' => 'Dual Tilt Semi-U Blade + Giant Variable Ripper',
                'hp_kw' => '636 HP / 474 kW',
                'year_build' => 2022,
                'date_receive' => '2022-05-10',
                'site_id' => $siteId,
                'remarks' => 'Heavy Dozer untuk Ripping Overburden Keras di Pit.',
            ],
            [
                'unit' => 'DZ-D10T-01',
                'no' => 302,
                'status' => 'Active',
                'reff_model' => 'D10T2',
                'sn_unit' => 'CAT0D10TJ00192',
                'engine_model' => 'CAT C27 ACERT V12',
                'sn_engine' => 'C27-D10T-9002',
                'eqp_capacity' => '22.0 m³ Full-U Blade',
                'no_police' => null,
                'attachment' => 'Universal Blade 22 m³ + Single Shank Ripper',
                'hp_kw' => '600 HP / 447 kW',
                'year_build' => 2021,
                'date_receive' => '2021-06-15',
                'site_id' => $siteId,
                'remarks' => 'Heavy Dozer Dozing & Ripping.',
            ],
            [
                'unit' => 'DZ-D8T-01',
                'no' => 303,
                'status' => 'Active',
                'reff_model' => 'D8T',
                'sn_unit' => 'CAT00D8TJ00881',
                'engine_model' => 'CAT C15 ACERT',
                'sn_engine' => 'C15-D8T-3321',
                'eqp_capacity' => '8.6 m³ Semi-U Blade',
                'no_police' => null,
                'attachment' => 'Semi-Universal Blade + Multi-Shank Ripper',
                'hp_kw' => '354 HP / 264 kW',
                'year_build' => 2023,
                'date_receive' => '2023-03-01',
                'site_id' => $siteAltId,
                'remarks' => 'Medium Dozer untuk Stockpile & Waste Dump Spreading.',
            ],
            [
                'unit' => 'DZ-D155-01',
                'no' => 304,
                'status' => 'Active',
                'reff_model' => 'D155AX-6',
                'sn_unit' => 'KMT-D155A-60119',
                'engine_model' => 'Komatsu SAA6D140E-5',
                'sn_engine' => '6D140-D155-882',
                'eqp_capacity' => '9.4 m³ Sigmadozer Blade',
                'no_police' => null,
                'attachment' => 'Sigmadozer Blade + Multi Shank Ripper',
                'hp_kw' => '354 HP / 264 kW',
                'year_build' => 2022,
                'date_receive' => '2022-09-18',
                'site_id' => $siteAltId,
                'remarks' => 'Dozer Waste Dump Leveling.',
            ],

            // ==========================================
            // 4. LIGHT VEHICLES (LV 4x4 Mine Spec)
            // ==========================================
            [
                'unit' => 'LV-HLX-01',
                'no' => 401,
                'status' => 'Active',
                'reff_model' => 'Hilux 2.4 G 4x4',
                'sn_unit' => 'MHF221199K00123',
                'engine_model' => 'Toyota 2GD-FTV 2.4L DOHC D-4D',
                'sn_engine' => '2GD-ENG-88192',
                'eqp_capacity' => '5 Penumpang / 1.0 Ton',
                'no_police' => 'KT 8101 AB',
                'attachment' => 'Rollbar Internal/External + Whip Flag + Strobe Light',
                'hp_kw' => '149 HP / 110 kW',
                'year_build' => 2023,
                'date_receive' => '2023-01-10',
                'site_id' => $siteId,
                'remarks' => 'Kendaraan Operasional Project Manager / Superintendent.',
            ],
            [
                'unit' => 'LV-HLX-02',
                'no' => 402,
                'status' => 'Active',
                'reff_model' => 'Hilux 2.4 G 4x4',
                'sn_unit' => 'MHF221199K00124',
                'engine_model' => 'Toyota 2GD-FTV 2.4L DOHC D-4D',
                'sn_engine' => '2GD-ENG-88193',
                'eqp_capacity' => '5 Penumpang / 1.0 Ton',
                'no_police' => 'KT 8102 AB',
                'attachment' => 'Safety Lightbar + VHF Mine Radio + First Aid Kit',
                'hp_kw' => '149 HP / 110 kW',
                'year_build' => 2023,
                'date_receive' => '2023-01-10',
                'site_id' => $siteId,
                'remarks' => 'Safety Patrol & SHE Inspection Unit.',
            ],
            [
                'unit' => 'LV-HLX-03',
                'no' => 403,
                'status' => 'Active',
                'reff_model' => 'Hilux 2.8 V 4x4',
                'sn_unit' => 'MHF221201K00451',
                'engine_model' => 'Toyota 1GD-FTV 2.8L High Output',
                'sn_engine' => '1GD-ENG-11029',
                'eqp_capacity' => '2 Penumpang + Mobile Tool Box',
                'no_police' => 'KT 8103 AB',
                'attachment' => 'Service Body + Air Compressor + Heavy Duty Tool Cabinet',
                'hp_kw' => '204 HP / 150 kW',
                'year_build' => 2024,
                'date_receive' => '2024-02-05',
                'site_id' => $siteId,
                'remarks' => 'Mobile Pit Breakdown Service Mekanik.',
            ],
            [
                'unit' => 'LV-TRT-01',
                'no' => 404,
                'status' => 'Active',
                'reff_model' => 'Triton 2.4 HDX 4x4',
                'sn_unit' => 'MMB100223A00912',
                'engine_model' => 'Mitsubishi 4N15 2.4L MIVEC Turbo',
                'sn_engine' => '4N15-ENG-77123',
                'eqp_capacity' => '5 Penumpang / 1.0 Ton',
                'no_police' => 'KT 8201 CD',
                'attachment' => 'Heavy Duty Bullbar + Winch 9.5T + Buggy Whip',
                'hp_kw' => '181 HP / 133 kW',
                'year_build' => 2022,
                'date_receive' => '2022-04-12',
                'site_id' => $siteAltId,
                'remarks' => 'Kendaraan Foreman Tambang & Pengawas Lapangan.',
            ],
            [
                'unit' => 'LV-DMX-01',
                'no' => 405,
                'status' => 'Active',
                'reff_model' => 'D-Max 3.0 Single Cabin 4x4',
                'sn_unit' => 'MP120099B00182',
                'engine_model' => 'Isuzu 4JJ3-TCX 3.0L BluePower',
                'sn_engine' => '4JJ3-ENG-90182',
                'eqp_capacity' => '2 Penumpang + 1000L Fuel Tank',
                'no_police' => 'KT 8301 EF',
                'attachment' => 'IBC Tank 1000L + 12V High Flow Fuel Pump + Hose',
                'hp_kw' => '190 HP / 140 kW',
                'year_build' => 2023,
                'date_receive' => '2023-08-20',
                'site_id' => $siteId,
                'remarks' => 'Fast Fuel & Lube Refill Pit Support.',
            ],
            [
                'unit' => 'LV-LC79-01',
                'no' => 406,
                'status' => 'Active',
                'reff_model' => 'Land Cruiser 79 Troop Carrier',
                'sn_unit' => 'JT711099A00281',
                'engine_model' => 'Toyota 1VD-FTV 4.5L V8 Turbo Diesel',
                'sn_engine' => '1VD-V8-88192',
                'eqp_capacity' => '10 Penumpang / Manhauler Rescue',
                'no_police' => 'KT 8401 GH',
                'attachment' => 'Heavy Duty Snorkel + Front/Rear Diff Lock + Stretcher Kit',
                'hp_kw' => '202 HP / 151 kW',
                'year_build' => 2022,
                'date_receive' => '2022-10-15',
                'site_id' => $siteId,
                'remarks' => 'Mine Emergency Response & Emergency Ambulance Unit.',
            ],

            // ==========================================
            // 5. MOTOR GRADERS & WHEEL LOADERS
            // ==========================================
            [
                'unit' => 'MG-24M-01',
                'no' => 501,
                'status' => 'Active',
                'reff_model' => '24M',
                'sn_unit' => 'CAT0024MJ00118',
                'engine_model' => 'CAT C18 ACERT',
                'sn_engine' => 'C18-24M-7719',
                'eqp_capacity' => '24 ft (7.3m) Heavy Moldboard',
                'no_police' => null,
                'attachment' => '24ft Heavy Duty Moldboard + Rear Ripper/Scarifier',
                'hp_kw' => '533 HP / 397 kW',
                'year_build' => 2021,
                'date_receive' => '2021-04-10',
                'site_id' => $siteId,
                'remarks' => 'Haul Road Maintenance Grader untuk jalur OHT 777/797.',
            ],
            [
                'unit' => 'MG-16M-01',
                'no' => 502,
                'status' => 'Active',
                'reff_model' => '16M',
                'sn_unit' => 'CAT0016MJ00452',
                'engine_model' => 'CAT C13 ACERT',
                'sn_engine' => 'C13-16M-9912',
                'eqp_capacity' => '16 ft (4.9m) Moldboard',
                'no_police' => null,
                'attachment' => '16ft Moldboard + 7-Tooth Ripper',
                'hp_kw' => '297 HP / 221 kW',
                'year_build' => 2022,
                'date_receive' => '2022-08-15',
                'site_id' => $siteAltId,
                'remarks' => 'Perawatan jalan tambang dan disposal.',
            ],
            [
                'unit' => 'WL-WA800-01',
                'no' => 503,
                'status' => 'Active',
                'reff_model' => 'WA800-3',
                'sn_unit' => 'KMT-WA800-30018',
                'engine_model' => 'Komatsu SAA12V140E-3',
                'sn_engine' => '12V140-WA800-112',
                'eqp_capacity' => '11.5 m³ Spade Nose Rock Bucket',
                'no_police' => null,
                'attachment' => 'High Lift Boom + Spade Nose Rock Bucket',
                'hp_kw' => '853 HP / 636 kW',
                'year_build' => 2021,
                'date_receive' => '2021-11-20',
                'site_id' => $siteId,
                'remarks' => 'Stockpile Crusher & Barge Loading Wheel Loader.',
            ],
            [
                'unit' => 'WL-980M-01',
                'no' => 504,
                'status' => 'Active',
                'reff_model' => '980M',
                'sn_unit' => 'CAT0980MJ00912',
                'engine_model' => 'CAT C13 ACERT',
                'sn_engine' => 'C13-980M-5512',
                'eqp_capacity' => '6.0 m³ General Purpose Bucket',
                'no_police' => null,
                'attachment' => 'Autolube + Heavy Duty Bucket dengan K290 Tips',
                'hp_kw' => '393 HP / 293 kW',
                'year_build' => 2023,
                'date_receive' => '2023-05-14',
                'site_id' => $siteAltId,
                'remarks' => 'Coal Loading & Blending Stockpile.',
            ],

            // ==========================================
            // 6. SUPPORT & UTILITY ANCILLARY
            // ==========================================
            [
                'unit' => 'WT-FUSO-01',
                'no' => 601,
                'status' => 'Active',
                'reff_model' => 'Fuso Fighter FM65FS Water 20kL',
                'sn_unit' => 'MHK-FM65FS-00812',
                'engine_model' => 'Mitsubishi 6M60 Common Rail 6-Cyl',
                'sn_engine' => '6M60-ENG-8819',
                'eqp_capacity' => '20,000 Liter (20 kL)',
                'no_police' => 'KT 8801 WT',
                'attachment' => 'Water Cannon Hidrolik + Rear Gravity Spray Bar + Fogging Nozzle',
                'hp_kw' => '240 HP / 177 kW',
                'year_build' => 2022,
                'date_receive' => '2022-03-01',
                'site_id' => $siteId,
                'remarks' => 'Water Truck penyiraman debu haul road 24 jam.',
            ],
            [
                'unit' => 'FT-HINO-01',
                'no' => 602,
                'status' => 'Active',
                'reff_model' => 'Hino 500 FM260TI Fuel 15kL',
                'sn_unit' => 'HIN-FM260TI-00419',
                'engine_model' => 'Hino J08E-UF 6-Cylinder Turbo',
                'sn_engine' => 'J08E-ENG-9012',
                'eqp_capacity' => '15,000 Liter Solar (B35)',
                'no_police' => 'KT 8901 FT',
                'attachment' => 'TCS Digital Flow Meter + Dual Reel High & Low Flow Nozzle',
                'hp_kw' => '260 HP / 191 kW',
                'year_build' => 2022,
                'date_receive' => '2022-06-15',
                'site_id' => $siteId,
                'remarks' => 'Fuel Truck pengisian solar alat berat di pit.',
            ],
            [
                'unit' => 'CR-TADANO-01',
                'no' => 603,
                'status' => 'Active',
                'reff_model' => 'GR-500EX 50T',
                'sn_unit' => 'TDN-GR500-00881',
                'engine_model' => 'Mitsubishi 6M60-TLU3B Turbo',
                'sn_engine' => '6M60-TDN-1123',
                'eqp_capacity' => '50 Ton Max Lift',
                'no_police' => null,
                'attachment' => '5-Section Rounded Boom 39.8m + Jib 13m',
                'hp_kw' => '267 HP / 200 kW',
                'year_build' => 2021,
                'date_receive' => '2021-08-20',
                'site_id' => $siteId,
                'remarks' => 'Rough Terrain Crane untuk bongkar pasang komponen berat di Workshop.',
            ],
            [
                'unit' => 'LT-ATLAS-01',
                'no' => 604,
                'status' => 'Active',
                'reff_model' => 'HiLight V4+ LED',
                'sn_unit' => 'AC-HLV4-0012',
                'engine_model' => 'Kubota Z482 Diesel 2-Cyl',
                'sn_engine' => 'KBT-Z482-881',
                'eqp_capacity' => '4x 350W High-Efficiency LED (4000 m²)',
                'no_police' => null,
                'attachment' => 'Hydraulic Mast 7.5m + Trailer Wheel Mount',
                'hp_kw' => '3.5 kVA / 2.8 kW',
                'year_build' => 2023,
                'date_receive' => '2023-02-01',
                'site_id' => $siteId,
                'remarks' => 'Tower Lamp Mobile penerangan kerja malam di Pit.',
            ],
            [
                'unit' => 'GEN-CAT-01',
                'no' => 605,
                'status' => 'Active',
                'reff_model' => 'CAT DE500 GC',
                'sn_unit' => 'CAT-DE500-0099',
                'engine_model' => 'CAT C13 Diesel Inline-6',
                'sn_engine' => 'C13-GEN-0091',
                'eqp_capacity' => '500 kVA / 400 kW Standby Power',
                'no_police' => null,
                'attachment' => 'Soundproof Weatherproof Acoustic Canopy 68 dBA',
                'hp_kw' => '500 kVA @ 1500 RPM',
                'year_build' => 2022,
                'date_receive' => '2022-01-15',
                'site_id' => $siteId,
                'remarks' => 'Genset Utama Workshop & Office Camp.',
            ],
        ];

        foreach ($equipmentList as $item) {
            $reffEquipId = $getReffId($item['reff_model']);

            Equipment::updateOrCreate(
                ['unit' => $item['unit']],
                [
                    'no' => $item['no'],
                    'status' => $item['status'],
                    'reff_equip_id' => $reffEquipId,
                    'sn_unit' => $item['sn_unit'],
                    'engine_model' => $item['engine_model'],
                    'sn_engine' => $item['sn_engine'],
                    'eqp_capacity' => $item['eqp_capacity'],
                    'no_police' => $item['no_police'],
                    'attachment' => $item['attachment'],
                    'hp_kw' => $item['hp_kw'],
                    'year_build' => $item['year_build'],
                    'date_receive' => $item['date_receive'],
                    'site_id' => $item['site_id'],
                    'remarks' => $item['remarks'],
                ]
            );
        }
    }
}
